language: node_js

jobs:
  include:
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 8
      install:
        - yarn global add @chialab/rna-cli
        - rna install
      script:
        - rna unit --node
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 7
      install:
        - yarn global add @chialab/rna-cli
        - rna install
      script:
        - rna unit --node
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=default
      node_js: 8
      install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - yarn global add @chialab/rna-cli
        - rna install
      script:
        - rna unit --browser
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 8
      install:
        - yarn global add @chialab/rna-cli
        - rna install
      script:
        - rna unit --saucelabs
  allow_failures:
    - env: "CI_BUILD_TYPE=saucelabs"
