language: node_js

jobs:
  include:
    - stage: test
    env: CI_BUILD_TYPE=default
    node_js: 8
    install:
      - export CHROME_BIN=chromium-browser
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - npm install -g @chialab/rna-cli
      - rna install
    script:
      - rna unit --browser
  - stage: test
    os: linux
    env: CI_BUILD_TYPE=saucelabs
    node_js: 8
    install:
      - npm install -g @chialab/rna-cli
      - rna install
    script:
      - rna unit --saucelabs
  allow_failures:
    - env: "CI_BUILD_TYPE=saucelabs"
