language: node_js

jobs:
  include:
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 10
      install:
        - yarn global add @chialab/rna-cli
        - yarn install
      script:
        - rna unit --node
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=default
      node_js: 10
      install:
        - export CHROME_BIN=chromium-browser
        - yarn global add @chialab/rna-cli
        - yarn install
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      script:
        - rna unit --browser --context test/unit/context.html
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 10
      install:
        - yarn global add @chialab/rna-cli
        - yarn install
      script:
        - rna unit --saucelabs --context test/unit/context.html
  allow_failures:
    - env: "CI_BUILD_TYPE=saucelabs"

services:
  - xvfb
